# spring
spring:
  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:mysql://127.0.0.1:13306/theater?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: wook
    password: qwer1234
# jpa
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect